#!/usr/bin/env bash

cmds=(
  "    install                      install the current (i.e. working state) of the repository into the jep_dev conda environment"
  "    test                         run the c3server jep unit tests"
  "    debug                        runs the jep unit tests and attaches a debugger"
  "    profile                      starts and pauses the jep unit tests while displaying the pid so that"
  "                                 you can attach a profiler (e.g. CLion Run -> Attach Profiler to Process)"
)


if [[ "${cmds[@]}" =~ "$1" ]]; then
  source "c3scripts/c3-jep-$1" $@
  exit $?
fi

echo ""
echo "usage: `basename $0` <command> [ PARAMS ]"
echo ""
echo "  commands:"
echo ""
for cmd in "${cmds[@]}" ; do
  echo "${cmd}"
done
echo ""
echo "  Note: The default test for test, debug, and profile is C3JepInterface_Test"
echo "  To run a different test, simply pass it as an argument after the command"
echo ""
echo ""

