package:
  name: c3jep
  version: {{ environ.get('GIT_DESCRIBE_TAG', "7.5.0") }}

source:
  path: ./

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

  # Note that this will override the default build string with the Python
  # and NumPy versions

requirements:
  build:
    - python # TODO WHICH VERSION?

  run:
    - python # TODO WHICH VERSION?

about:
  home: https://github.com/c3-e/jep
  license: Copyright 2009-2020 C3 (www.c3.ai). All Rights Reserved.
  license_file: LICENSE