#!/usr/bin/env bash
set -e

TEST=${2:-C3JepInterface_Test}

# Assume ./c3-conda install has been run
#CONDA_BASE=$(conda info --base)
#source $CONDA_BASE/etc/profile.d/conda.sh
#
#conda activate jep_dev

cd $C3_SERVER_ROOT && JEP_DEV_MODE=True ./v8 test --tests $TEST
