#!/usr/bin/env bash
set -e

source ./c3scripts/c3-jep-utils

ensure_test_output_dir

TEST=${2:-C3JepInterface_Test}
CUR_DIR=$(pwd)
TEST_OUTPUT_FILE=$CUR_DIR"/"$TEST_OUTPUT_DIR"/"$TEST"."$(date "+%H.%M.%S-%Y.%m.%d")

echo ""
echo "Launching test "$TEST
# execute tests in a forked process
# --debug-jvm flag to make sure that the gradle process waits so we can grab the pid before attaching
# a debugger or profiler
cd $C3_SERVER_ROOT && JEP_DEV_MODE=True ./v8 test --tests $TEST --debug-jvm > $TEST_OUTPUT_FILE 2>&1 &

echo ""
echo "Getting pid for test process. Please wait while the test starts."
echo ""
GRADLE_TESTER_PID=$(get_test_pid | awk '{ print $NF }' | tail -1)
echo "Gradle Tester PID: " $GRADLE_TESTER_PID
echo ""

read -n 1 -s -r -p "Please connect to the CLion Profiler (Run -> Attach Profiler to Process) and then press any key to allow the test to resume."

# attach to jvm process so that the test begins to execute
echo "run" | jdb -attach 5005 > /dev/null 2>&1 &
